changelog:
  categories:
    - title: Features
      labels:
        - enhancement
    - title: Documentation
      labels:
        - documentation
    - title: Security
      labels:
        - security
    - title: Dependency updates
      labels:
        - dependencies
